### ISSUE TITLE
def Theta(x) in lecture 2

### ISSUE THREAD

**Issue by AlJohri** [jrjohansson/scientific-python-lectures#38]
any reason for the capitalized function, Theta, in lecture 2? just curious if I'm missing anything specific to vectorizing ufuncs in numpy

**Comment by jrjohansson** [comment]
Hi Sorry for the slow reply. The only reason for the name Theta with capital T is that the heaviside function is often represented with the capital greek symbol theta, and in latex this symbol is writen Theta.
