### ISSUE TITLE
Problem using your Makefile to build a PDF using latest Anaconda 4.0.0 Python 3.5.1 

### ISSUE THREAD

**Issue by jrminter** [jrjohansson/scientific-python-lectures#39]
First, let me say that I have greatly benefited from these lectures. The ability to build a PDF with a LaTeX template is an added bonus. I'm using the latest Anaconda Python and I would like to use your Makefile to build PDF's. I noticed others posted a similar desire previously. I'm posting this as a new issue because I have a specific error message and was hoping you might have encountered this using the latest jupyter notebook. I also assume you will also want to migrate to this current tool chain, if you have not already.

I am using the following syntax in the `latexfiles` section of the Makefile

```
jupyter nbconvert --to latex --template $(TEMPLATE) filename.ipynb
```

This fails with an error in `pygments`

```
File "C:\Apps\Anaconda3\lib\site-packages\pygments\util.py", line 309, in guess_decode
    text = text.decode('utf-8')
jinja2.exceptions.UndefinedError: 'nbformat.notebooknode.NotebookNode object' has no attribute 'input'
```

I should also note that my small test notebooks download to PDF individually through the browser. I just can't get the template and Makefile to work. 

Thank you.

**Comment by jrjohansson** [comment]
Hi and thanks for your kind words, and for reporting the build problems. I have updated the template and the Makefile and for me it now works with latest version of jupyter.
