### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by SimonBiggs** [jrjohansson/scientific-python-lectures#47]
Hi, 

I'm hoping to be able to use your notebooks as a primer for a medical physics programming workshop. However at this point in time if someone is starting out they should begin with Python 3.

Are there any plans to port to Python 3? I would be willing to help.

Cheers,
Simon

**Comment by jrjohansson** [comment]
Hi. Thanks for your interest. I agree, at this point in time Python 3 should be the focus. Maybe the narrative is somewhat biased to Python 2, but I think that most of the code is mostly Python 3 compatible. So I think that it should not be a big job to port these notebooks to Python 3. Right now I dont have much time to work on it, but if you want to contribute on this it would be much appreciated.

**Comment by SimonBiggs** [comment]
I'll see how much I can port across tonight. See if I can get a pull request to you soonish. 

Would you be okay if I highly prioritise Anaconda as a recommendation for installation? My thoughts are to make installation recommendations be more inline with the following document:
http://nbviewer.jupyter.org/github/ipython-books/minibook-2nd-code/blob/master/chapter1/12-installation.ipynb

**Comment by SimonBiggs** [comment]
Completed in pull request #48

**Comment by jondo** [comment]
Also see #58.
